### ISSUE TITLE
Build fails on MacOS

### ISSUE THREAD

**Issue by cloudkucooland** [warthog618/go-gpiocdev#49]
Low priority since the program using this module targets Raspberry Pi devices, but I build my stuff on my macbook from time to time. I also build on OpenBSD without issue.

I glanced around for build tags which might be causing the issue, but I couldn't find anything.

I'd like to have this build, even if it doesn't actually do anything, on MacOS.

scot@Scots-MacBook-Air:/Users/scot/Documents/GitHub/HVAC % !go
go install -v ./...
github.com/warthog618/go-gpiocdev
# github.com/warthog618/go-gpiocdev
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/options.go:93:50: undefined: uapi.OutputValues
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/options.go:101:34: undefined: uapi.LineConfigAttribute
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/gpiocdev.go:325:35: undefined: uapi.LineInfo
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/gpiocdev.go:350:37: undefined: uapi.LineInfoV2
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/gpiocdev.go:390:26: undefined: uapi.LineInfo
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/gpiocdev.go:400:28: undefined: uapi.LineInfoV2
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/gpiocdev.go:595:43: undefined: uapi.HandleFlag
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/gpiocdev.go:628:42: undefined: uapi.EventFlag
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/gpiocdev.go:641:49: undefined: uapi.LineFlagV2
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/gpiocdev.go:678:55: undefined: uapi.LineAttribute
../../../go/pkg/mod/github.com/warthog618/go-gpiocdev@v0.9.0/options.go:93:50: too many errors

**Comment by warthog618** [comment]
Refer to issue #36.
