### ISSUE TITLE
undefined some uapi package

### ISSUE THREAD

**Issue by Jaxx1911** [warthog618/go-gpiocdev#52]
<img width="905" alt="Screen Shot 2024-07-20 at 11 38 57" src="https://github.com/user-attachments/assets/3499b124-3f8c-4d77-8275-04b56b19f57b">
Why i have this error when trying to use your lib :(( Pls help

**Comment by warthog618** [comment]
I can't even tell what you are doing, so no idea.
What did you do to produce that?
And don't post images - cut and paste text instead.

**Comment by warthog618** [comment]
Ahh, are you building on Windows or Mac?  This library is Linux specific. Check the [installation instructions](https://github.com/warthog618/go-gpiocdev#installation) if you are having problems during installation. e.g.

```
go get -d github.com/warthog618/go-gpiocdev
```

And if building on a non-Linux platform you need to setup the cross-compilation variables, e.g.

```
$ GOOS=linux GOARCH=arm GOARM=6 go build
```

**Comment by Jaxx1911** [comment]
Thanks u so much :33
